#!/usr/bin/env node
/**
 * ArcKit PostToolUse (Write|Edit) Hook — Build Provenance Stamping
 *
 * Stamps a "## Build Provenance" block into ArcKit artefact files,
 * complementing — not duplicating — the human-authored footer that the
 * generating command writes ("Generated by:", "AI Model:", etc.). The
 * block carries only fields the model can't authoritatively self-report:
 *
 *   - Build context (recipe, wave, target ID, topic) when the run came
 *     from /arckit:build via .arckit/state.json
 *   - Requested Effort (from command frontmatter)
 *   - Effective Effort (after silent-downgrade for non-Opus models —
 *     computed from the model self-reported in the existing footer)
 *
 * The block is delimited by HTML comments so the hook is idempotent —
 * re-running on the same file replaces the existing block in place rather
 * than appending duplicates.
 *
 * Sources of truth (in order of preference per field):
 *   - Skill:           state.json target.skill (build-harness runs only)
 *   - Build context:   .arckit/state.json (only when run via /arckit:build)
 *   - Effort:          arckit-claude/commands/{name}.md frontmatter
 *   - Model:           "AI Model:" line in the existing footer (model
 *                      self-reports during generation; we trust that)
 *
 * Fields ALREADY in the existing footer (and therefore not stamped here):
 *   - Generated by / Skill name
 *   - Generated on date
 *   - ArcKit Version
 *   - Project name
 *   - AI Model
 *   - Generation Context / Inputs (BR/FR/NFR IDs the model actually used)
 *
 * If you want one of those, parse the existing footer.
 *
 * Guards (exit silently if any fail):
 *   - tool_name not Write or Edit
 *   - file_path not under /projects/
 *   - filename doesn't match ARC-NNN-*-vN.N.md
 *   - file isn't readable / writable
 *
 * Hook Type: PostToolUse
 * Matcher:   Write|Edit
 * Input:     JSON { tool_name, tool_input: { file_path }, cwd }
 * Output:    none
 * Exit:      0 always
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isFile, findRepoRoot, parseHookInput } from './hook-utils.mjs';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ── Effort downgrade matrix ────────────────────────────────────────────
// Mirrors the Claude Code harness behaviour: effort levels not supported
// by the active model are silently downgraded to the highest supported.
const EFFORT_RANK = { low: 0, medium: 1, high: 2, max: 3, xhigh: 4 };
const MODEL_MAX_EFFORT = {
  'claude-opus-4-7': 'xhigh',
  'claude-opus-4-6': 'max',
  'claude-sonnet-4-6': 'high',
  'claude-haiku-4-5': 'medium',
};

function downgradeEffort(requested, model) {
  if (!requested) return null;
  if (!model) return null;
  const cap = MODEL_MAX_EFFORT[model];
  if (!cap) return requested;
  if (EFFORT_RANK[requested] <= EFFORT_RANK[cap]) return requested;
  return cap;
}

// ── Provenance block delimiters ────────────────────────────────────────
const PROV_START = '<!-- arckit-provenance:start -->';
const PROV_END = '<!-- arckit-provenance:end -->';

// ── Field readers ──────────────────────────────────────────────────────

function readCommandFrontmatter(commandName) {
  if (!commandName) return {};
  const p = join(PLUGIN_ROOT, 'commands', `${commandName}.md`);
  if (!isFile(p)) return {};
  let content;
  try {
    content = readFileSync(p, 'utf8');
  } catch {
    return {};
  }
  const m = content.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return {};
  const yaml = m[1];
  const result = {};
  const effort = yaml.match(/^effort:\s*(\S+)/m);
  if (effort) result.effort = effort[1];
  return result;
}

// Detect command from existing footer ("Generated by: ArcKit `/arckit:X` command")
// Supports both /arckit:X and /arckit.X forms.
function extractCommandFromContent(content) {
  const m = content.match(/Generated by[^`\n]*`\/?arckit[:.]([a-z0-9-]+)`/i);
  return m ? m[1] : null;
}

// Detect model from existing footer ("AI Model: claude-opus-4-7" or "Model: ...").
// Trusts the model's self-report — that's what's in the human-authored footer
// today and is the only source of truth until upstream Claude Code exposes
// the active model to hooks (see arc-kit#407).
function extractModelFromContent(content) {
  const m = content.match(/^\s*\*?\*?(?:AI )?Model\*?\*?:\s*`?([a-z0-9.-]+)`?\s*$/im);
  return m ? m[1].trim() : null;
}

function findBuildContext(filePath, repoRoot) {
  if (!repoRoot) return null;
  const m = filePath.match(/\/projects\/([^/]+)\//);
  if (!m) return null;
  const projectDir = m[1];
  const statePath = join(repoRoot, 'projects', projectDir, '.arckit', 'state.json');
  if (!isFile(statePath)) return null;

  let state;
  try {
    state = JSON.parse(readFileSync(statePath, 'utf8'));
  } catch {
    return null;
  }

  // Match by filename basename — state.json paths may be relative or absolute,
  // and may not match repoRoot exactly across symlinks/tmp dirs.
  const wantBase = basename(filePath);
  const targets = state.targets || {};
  for (const [id, t] of Object.entries(targets)) {
    if (!t.path) continue;
    if (basename(t.path) === wantBase) {
      return {
        recipe: state.recipe || null,
        wave: t.wave ?? null,
        target: id,
        skill: t.skill || null,
        topic: t.topic || null,
      };
    }
  }
  return null;
}

// ── Block construction ────────────────────────────────────────────────
//
// The block carries ONLY harness-derived fields that complement the existing
// human-authored footer. We deliberately do NOT restamp Skill, Model,
// Generated-on, ArcKit Version, or Project — those are already in the footer
// and the model self-reports them at generation time.

function buildProvenanceBlock(fields) {
  const {
    effort_requested,
    effort_effective,
    effort_downgraded,
    build,
    timestamp,
  } = fields;

  // Skip the block entirely if there is nothing harness-only to record.
  if (!effort_requested && !build) return null;

  const rows = [];

  if (effort_requested) {
    rows.push(['Requested Effort', `\`${effort_requested}\``]);
    if (effort_effective) {
      rows.push([
        'Effective Effort',
        effort_downgraded
          ? `\`${effort_effective}\` (downgraded from \`${effort_requested}\` — model does not support that level)`
          : `\`${effort_effective}\``,
      ]);
    } else {
      rows.push([
        'Effective Effort',
        '_unknown — model not parsed from existing footer_',
      ]);
    }
  }

  if (build) {
    rows.push(['Build Recipe', build.recipe ? `\`${build.recipe}\`` : '_unknown_']);
    if (build.wave !== null) rows.push(['Build Wave', String(build.wave)]);
    rows.push(['Build Target', `\`${build.target}\``]);
    if (build.topic) rows.push(['Build Topic', build.topic]);
  }

  rows.push(['Stamped at', timestamp]);

  let body = `${PROV_START}\n\n## Build Provenance\n\n_Stamped automatically by the ArcKit plugin's \`provenance-stamp.mjs\` PostToolUse hook. Complements (does not replace) the human-authored footer above. Carries only fields the model can't authoritatively self-report: build context from \`.arckit/state.json\` and effort levels derived from command frontmatter + the silent-downgrade matrix._\n\n| Field | Value |\n|-------|-------|\n`;
  for (const [k, v] of rows) body += `| ${k} | ${v} |\n`;
  body += `\n${PROV_END}\n`;
  return body;
}

// ── File update ────────────────────────────────────────────────────────

function stampFile(filePath, block) {
  let content;
  try {
    content = readFileSync(filePath, 'utf8');
  } catch {
    return false;
  }

  const startIdx = content.indexOf(PROV_START);
  const endIdx = content.indexOf(PROV_END);

  let newContent;
  if (startIdx >= 0 && endIdx > startIdx) {
    // Replace existing block. Trim trailing newline that follows PROV_END.
    const before = content.slice(0, startIdx);
    const afterStart = endIdx + PROV_END.length;
    const after = content.slice(afterStart).replace(/^\n/, '');
    newContent = before + block + (after.length ? '\n' + after : '');
  } else {
    // Append. Ensure single blank line separator.
    if (!content.endsWith('\n')) content += '\n';
    if (!content.endsWith('\n\n')) content += '\n';
    newContent = content + block;
  }

  if (newContent === content) return false;

  try {
    writeFileSync(filePath, newContent);
    return true;
  } catch {
    return false;
  }
}

// ── Main ──────────────────────────────────────────────────────────────

const data = parseHookInput();
const tool = data.tool_name;
if (tool !== 'Write' && tool !== 'Edit') process.exit(0);

const filePath = data.tool_input?.file_path;
if (!filePath) process.exit(0);
if (!filePath.includes('/projects/')) process.exit(0);

const fname = basename(filePath);
if (!/^ARC-\d{3}-.+-v\d+(\.\d+)?\.md$/.test(fname)) process.exit(0);
if (!isFile(filePath)) process.exit(0);

const repoRoot = findRepoRoot(data.cwd) || dirname(filePath);

let content;
try {
  content = readFileSync(filePath, 'utf8');
} catch {
  process.exit(0);
}

// Resolve fields
const build = findBuildContext(filePath, repoRoot);
const command = extractCommandFromContent(content);
const fm = command ? readCommandFrontmatter(command) : {};
const model = extractModelFromContent(content);

const effortRequested = fm.effort || null;
const effortEffective = downgradeEffort(effortRequested, model);
const effortDowngraded =
  effortEffective !== null && effortRequested !== null && effortEffective !== effortRequested;

const block = buildProvenanceBlock({
  effort_requested: effortRequested,
  effort_effective: effortEffective,
  effort_downgraded: effortDowngraded,
  build,
  timestamp: new Date().toISOString(),
});

if (block !== null) stampFile(filePath, block);
process.exit(0);
