#!/usr/bin/env node
/**
 * ArcKit PostToolUse (Write|Edit) Hook — Provenance Stamping
 *
 * Stamps a derived provenance block into ArcKit artefact files immediately
 * after they are written or edited. The block records:
 *
 *   - Skill that produced the artefact (e.g. arckit:requirements)
 *   - Generated-on ISO timestamp
 *   - ArcKit plugin version
 *   - Build context (recipe, wave, target ID) when the run came from
 *     /arckit:build via .arckit/state.json
 *   - Requested effort (from command frontmatter)
 *   - Effective effort (after silent-downgrade for non-Opus models)
 *
 * The block is delimited by HTML comments so the hook is idempotent —
 * re-running on the same file replaces the existing block in place rather
 * than appending duplicates.
 *
 * Sources of truth (in order of preference per field):
 *   - Skill:           state.json target.skill → `arckit:` + invoking command
 *   - Build context:   .arckit/state.json (only when run via /arckit:build)
 *   - Effort:          arckit-claude/commands/{name}.md frontmatter
 *   - Model:           transcript_path (last assistant turn) — see TODO below
 *   - ArcKit version:  arckit-claude/VERSION
 *
 * Model resolution from transcript is left as a TODO — the hook emits
 * a placeholder until upstream Claude Code surfaces the active model
 * through hook payload (see arc-kit#407 / claude-code#55829).
 *
 * Guards (exit silently if any fail):
 *   - tool_name not Write or Edit
 *   - file_path not under /projects/
 *   - filename doesn't match ARC-NNN-*-vN.N.md
 *   - file isn't readable / writable
 *
 * Hook Type: PostToolUse
 * Matcher:   Write|Edit
 * Input:     JSON { tool_name, tool_input: { file_path }, cwd }
 * Output:    none
 * Exit:      0 always
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isFile, findRepoRoot, parseHookInput } from './hook-utils.mjs';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ── Effort downgrade matrix ────────────────────────────────────────────
// Mirrors the Claude Code harness behaviour: effort levels not supported
// by the active model are silently downgraded to the highest supported.
const EFFORT_RANK = { low: 0, medium: 1, high: 2, max: 3, xhigh: 4 };
const MODEL_MAX_EFFORT = {
  'claude-opus-4-7': 'xhigh',
  'claude-opus-4-6': 'max',
  'claude-sonnet-4-6': 'high',
  'claude-haiku-4-5': 'medium',
};

function downgradeEffort(requested, model) {
  if (!requested) return null;
  if (!model) return null;
  const cap = MODEL_MAX_EFFORT[model];
  if (!cap) return requested;
  if (EFFORT_RANK[requested] <= EFFORT_RANK[cap]) return requested;
  return cap;
}

// ── Provenance block delimiters ────────────────────────────────────────
const PROV_START = '<!-- arckit-provenance:start -->';
const PROV_END = '<!-- arckit-provenance:end -->';

// ── Field readers ──────────────────────────────────────────────────────

function readArckitVersion() {
  const p = join(PLUGIN_ROOT, 'VERSION');
  if (!isFile(p)) return 'unknown';
  try {
    return readFileSync(p, 'utf8').trim();
  } catch {
    return 'unknown';
  }
}

function readCommandFrontmatter(commandName) {
  if (!commandName) return {};
  const p = join(PLUGIN_ROOT, 'commands', `${commandName}.md`);
  if (!isFile(p)) return {};
  let content;
  try {
    content = readFileSync(p, 'utf8');
  } catch {
    return {};
  }
  const m = content.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return {};
  const yaml = m[1];
  const result = {};
  const effort = yaml.match(/^effort:\s*(\S+)/m);
  if (effort) result.effort = effort[1];
  return result;
}

// Detect command from existing footer ("Generated by: ArcKit `/arckit:X` command")
// Supports both /arckit:X and /arckit.X forms.
function extractCommandFromContent(content) {
  const m = content.match(/Generated by[^`\n]*`\/?arckit[:.]([a-z0-9-]+)`/i);
  return m ? m[1] : null;
}

function findBuildContext(filePath, repoRoot) {
  if (!repoRoot) return null;
  const m = filePath.match(/\/projects\/([^/]+)\//);
  if (!m) return null;
  const projectDir = m[1];
  const statePath = join(repoRoot, 'projects', projectDir, '.arckit', 'state.json');
  if (!isFile(statePath)) return null;

  let state;
  try {
    state = JSON.parse(readFileSync(statePath, 'utf8'));
  } catch {
    return null;
  }

  // Match by filename basename — state.json paths may be relative or absolute,
  // and may not match repoRoot exactly across symlinks/tmp dirs.
  const wantBase = basename(filePath);
  const targets = state.targets || {};
  for (const [id, t] of Object.entries(targets)) {
    if (!t.path) continue;
    if (basename(t.path) === wantBase) {
      return {
        recipe: state.recipe || null,
        wave: t.wave ?? null,
        target: id,
        skill: t.skill || null,
        topic: t.topic || null,
      };
    }
  }
  return null;
}

// ── Block construction ────────────────────────────────────────────────

function buildProvenanceBlock(fields) {
  const {
    skill,
    effort_requested,
    effort_effective,
    model,
    arckit_version,
    build,
    timestamp,
  } = fields;

  const rows = [];
  rows.push(['Skill', skill ? `\`${skill}\`` : '_unknown_']);
  rows.push(['Generated on', timestamp]);
  rows.push(['ArcKit Version', arckit_version]);

  if (model) {
    rows.push(['Model', `\`${model}\``]);
  } else {
    rows.push(['Model', '_not yet exposed by Claude Code (see arc-kit#407)_']);
  }

  if (effort_requested) {
    rows.push(['Requested Effort', `\`${effort_requested}\``]);
    if (effort_effective) {
      const downgraded = effort_effective !== effort_requested;
      rows.push([
        'Effective Effort',
        downgraded
          ? `\`${effort_effective}\` (downgraded — model does not support \`${effort_requested}\`)`
          : `\`${effort_effective}\``,
      ]);
    }
  }

  if (build) {
    rows.push(['Build Recipe', build.recipe ? `\`${build.recipe}\`` : '_unknown_']);
    if (build.wave !== null) rows.push(['Build Wave', String(build.wave)]);
    rows.push(['Build Target', `\`${build.target}\``]);
    if (build.topic) rows.push(['Build Topic', build.topic]);
  }

  let body = `${PROV_START}\n\n## Provenance\n\n_Stamped automatically by the ArcKit plugin's PostToolUse hook. Derived from \`.arckit/state.json\` (build context) and command frontmatter (effort). See arc-kit#407 for the gaps._\n\n| Field | Value |\n|-------|-------|\n`;
  for (const [k, v] of rows) body += `| ${k} | ${v} |\n`;
  body += `\n${PROV_END}\n`;
  return body;
}

// ── File update ────────────────────────────────────────────────────────

function stampFile(filePath, block) {
  let content;
  try {
    content = readFileSync(filePath, 'utf8');
  } catch {
    return false;
  }

  const startIdx = content.indexOf(PROV_START);
  const endIdx = content.indexOf(PROV_END);

  let newContent;
  if (startIdx >= 0 && endIdx > startIdx) {
    // Replace existing block. Trim trailing newline that follows PROV_END.
    const before = content.slice(0, startIdx);
    const afterStart = endIdx + PROV_END.length;
    const after = content.slice(afterStart).replace(/^\n/, '');
    newContent = before + block + (after.length ? '\n' + after : '');
  } else {
    // Append. Ensure single blank line separator.
    if (!content.endsWith('\n')) content += '\n';
    if (!content.endsWith('\n\n')) content += '\n';
    newContent = content + block;
  }

  if (newContent === content) return false;

  try {
    writeFileSync(filePath, newContent);
    return true;
  } catch {
    return false;
  }
}

// ── Main ──────────────────────────────────────────────────────────────

const data = parseHookInput();
const tool = data.tool_name;
if (tool !== 'Write' && tool !== 'Edit') process.exit(0);

const filePath = data.tool_input?.file_path;
if (!filePath) process.exit(0);
if (!filePath.includes('/projects/')) process.exit(0);

const fname = basename(filePath);
if (!/^ARC-\d{3}-.+-v\d+(\.\d+)?\.md$/.test(fname)) process.exit(0);
if (!isFile(filePath)) process.exit(0);

const repoRoot = findRepoRoot(data.cwd) || dirname(filePath);

let content;
try {
  content = readFileSync(filePath, 'utf8');
} catch {
  process.exit(0);
}

// Resolve fields
const build = findBuildContext(filePath, repoRoot);
const command = extractCommandFromContent(content);
const fm = command ? readCommandFrontmatter(command) : {};

// Skill: prefer build context (authoritative), fall back to command-derived
const skill = build?.skill || (command ? `arckit:${command}` : null);

const effortRequested = fm.effort || null;
// Model resolution from transcript_path is a future enhancement —
// today the active model is not exposed to hooks (see arc-kit#407).
const model = null;
const effortEffective = downgradeEffort(effortRequested, model);

const block = buildProvenanceBlock({
  skill,
  effort_requested: effortRequested,
  effort_effective: effortEffective,
  model,
  arckit_version: readArckitVersion(),
  build,
  timestamp: new Date().toISOString(),
});

stampFile(filePath, block);
process.exit(0);
