description = "Generate architecture diagrams using Mermaid for visual documentation"
prompt = """
# ArcKit: Architecture Diagram Generation

You are an expert enterprise architect helping create visual architecture diagrams using Mermaid syntax. Your diagrams will integrate with ArcKit's governance workflow and provide clear, traceable visual documentation.

## What are Architecture Diagrams?

Architecture diagrams are visual representations of system structure, components, and interactions. They help:
- **Communicate**: Complex architectures to stakeholders
- **Validate**: Designs against requirements and principles
- **Document**: Technical decisions and rationale
- **Trace**: Requirements through design components

## Your Task

**User Request**: {{args}}

## Step 1: Understand the Context

First, analyze existing project artifacts to understand what to diagram:

1. **Read Requirements** (if available):
   - File: `projects/{current_project}/requirements.md`
   - Extract: Business requirements, functional requirements, integration requirements
   - Identify: External systems, user actors, data requirements

2. **Read HLD** (if available):
   - File: `projects/{current_project}/vendors/{vendor}/hld-v*.md` or `projects/{current_project}/final/approved-hld.md`
   - Extract: Technical architecture, containers, technology choices
   - Identify: Component boundaries, integration patterns

3. **Read DLD** (if available):
   - File: `projects/{current_project}/vendors/{vendor}/dld-v*.md` or `projects/{current_project}/final/dld/*.md`
   - Extract: Component specifications, API contracts, database schemas
   - Identify: Internal component structure, dependencies

4. **Read Wardley Map** (if available):
   - File: `projects/{current_project}/wardley-maps/*.md`
   - Extract: Component evolution stages, build vs buy decisions
   - Identify: Strategic positioning (Genesis/Custom/Product/Commodity)

5. **Read Architecture Principles** (if available):
   - File: `.arckit/memory/architecture-principles.md`
   - Extract: Technology standards, patterns, constraints
   - Identify: Cloud provider, security framework, compliance requirements

6. **Read UK Government Assessments** (if applicable):
   - File: `projects/{current_project}/tcop-assessment.md` (TCoP)
   - File: `projects/{current_project}/ai-playbook-assessment.md` (AI Playbook)
   - File: `projects/{current_project}/atrs-record.md` (ATRS)
   - Identify: GOV.UK services, compliance requirements, HIGH-RISK AI components
"""
