description = "Analyze stakeholder drivers, goals, and measurable outcomes"
prompt = """
You are helping an enterprise architect or project manager understand stakeholder drivers, how they manifest into goals, and what measurable outcomes will satisfy each stakeholder.

## User Input

```text
{{args}}
```

## Instructions

1. **Create or find the project**:
   - Run `.arckit/scripts/bash/create-project.sh --name "$PROJECT_NAME" --json` to create project structure
   - Parse the JSON output to get the project directory path
   - Or if the user specifies an existing project number (e.g., "001"), use that directory

2. **Read the template**: Read `.arckit/templates/stakeholder-drivers-template.md` to understand the comprehensive structure

3. **Check for existing context**:
   - If `.arckit/memory/architecture-principles.md` exists, read it to understand organizational context
   - If `projects/{project}/requirements.md` exists, read it to understand stakeholder mentions
   - Use this context to make the analysis more realistic and aligned

4. **Analyze and generate stakeholder drivers analysis** based on user input:

   **Phase 1: Identify Stakeholders**
   - List all relevant internal stakeholders (executives, business units, technical teams, operations, compliance, security, finance)
   - List external stakeholders (regulators, customers, vendors, partners)
   - Create a Power-Interest grid showing who needs what level of engagement

   **Phase 2: Understand Drivers**
   For each key stakeholder, identify:
   - **STRATEGIC drivers**: Competitive advantage, market position, innovation
   - **OPERATIONAL drivers**: Efficiency, quality, speed, reliability
   - **FINANCIAL drivers**: Cost reduction, revenue growth, ROI
   - **COMPLIANCE drivers**: Regulatory requirements, audit findings, risk mitigation
   - **PERSONAL drivers**: Career advancement, workload reduction, reputation
   - **RISK drivers**: Avoiding penalties, preventing failures, reducing exposure
   - **CUSTOMER drivers**: Satisfaction, retention, acquisition

   For each driver, document:
   - Clear driver statement (what motivates them)
   - Context & background (why this exists)
   - Intensity (CRITICAL | HIGH | MEDIUM | LOW)
   - Enablers (what would help)
   - Blockers (what would hinder)

   **Phase 3: Map Drivers to Goals**
   - Convert each driver into specific, measurable SMART goals
   - Show which drivers feed into which goals (one goal may satisfy multiple drivers)
   - Define success metrics, baselines, targets, and measurement methods
   - Identify dependencies and risks to goal achievement

   Example: Driver "Reduce operational costs" → Goal "Reduce invoice processing time from 7 days to 2 days by Q2 2026"

   **Phase 4: Map Goals to Outcomes**
   - Define measurable business outcomes that prove goals are achieved
   - Specify KPIs, current values, target values, measurement frequency
   - Quantify business value (financial, strategic, operational, customer impact)
   - Define timeline with phase targets
   - Identify leading indicators (early signals) and lagging indicators (final proof)

   Example: Goal "Reduce processing time" → Outcome "30% operational efficiency increase measured by transactions per FTE"

   **Phase 5: Traceability Matrix**
   - Create complete Stakeholder → Driver → Goal → Outcome traceability table
   - Identify conflicts (competing drivers between stakeholders)
   - Identify synergies (drivers that align across stakeholders)
   - Propose resolution strategies for conflicts

   **Phase 6: Engagement Plan**
   - Create stakeholder-specific messaging addressing their drivers
   - Define communication frequency and channels
   - Assess change impact and resistance risk
   - Identify champions, fence-sitters, and resisters

   **Phase 7: Governance**
   - Define RACI matrix for key decisions
   - Document escalation path
   - Create risk register for stakeholder-related risks

5. **Make it actionable and realistic**:
   - Use real-world metrics and timeframes
   - Be specific about measurement methods
   - Acknowledge conflicts honestly
   - Provide practical resolution strategies
   - Include both quantitative and qualitative measures
   - Consider UK Government context if applicable (Minister accountability, public scrutiny, parliamentary questions, transparency requirements)

6. **Write the output**:
   - Write to `projects/{project-dir}/stakeholder-drivers.md`
   - Use the exact template structure
   - Fill in ALL sections with realistic, thoughtful analysis
   - DO NOT leave sections as TBD unless genuinely unknown

7. **Summarize what you created**:
   - How many stakeholders analyzed
   - How many drivers identified
   - How many goals defined
   - How many outcomes mapped
   - Key conflicts or risks
   - Critical success factors
   - Suggested next steps: "Now run `/arckit.requirements` to create requirements that align with and address these stakeholder goals and drivers"
"""
