#!/usr/bin/env node
/**
 * /arckit:pages confidentiality defaults (sync-guides.mjs).
 *
 * A client risk review found that one command put three things into docs/
 * with no prompt and no warning: a ranked summary of vendors/scores.json in
 * manifest.json, an llms.txt index built for AI crawlers with direct links to
 * every artefact, and every vendor document in the index. docs/ only goes
 * public when a user commits and pushes it, but nothing said so.
 *
 * Now:
 *   - the vendor ranking is left out of manifest.json unless VENDOR_SCORES=true
 *   - llms.txt is written only with LLMS=true; an earlier generated one is
 *     removed, a hand-curated one is left alone
 *   - every run reports a CONFIDENTIALITY section the command must show,
 *     naming artefacts marked above OFFICIAL
 *   - the flags are read only from the user's arguments, never from the
 *     command body, which documents them
 *
 * NOTE the filename: CI runs `tests/plugin/*.test.mjs`.
 */

import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import test from 'node:test';

const PLUGIN_ROOT = resolve(import.meta.dirname, '../../plugins/arckit-claude');
const HOOK = join(PLUGIN_ROOT, 'hooks/sync-guides.mjs');
const MARKER = '<!-- Generated by ArcKit /arckit:pages -->';

function git(cwd, ...args) {
  const r = spawnSync('git', args, { cwd, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`git ${args.join(' ')}: ${r.stderr}`);
}

function runHook(repoRoot, prompt) {
  const r = spawnSync('node', [HOOK], {
    cwd: repoRoot,
    input: JSON.stringify({ prompt, cwd: repoRoot }),
    encoding: 'utf8',
    env: { ...process.env, CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT },
    timeout: 60000,
  });
  assert.equal(r.status, 0, `hook failed: ${r.stderr}`);
  return JSON.parse(r.stdout).hookSpecificOutput.additionalContext;
}

const doc = (id, classification) => `# ${id}

| Field | Value |
|-------|-------|
| **Document ID** | ${id} |
| **Classification** | ${classification} |
`;

function withRepo(fn, { priorLlms = null } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'arckit-pages-conf-'));
  try {
    git(dir, 'init', '-q');
    const p = join(dir, 'projects/001-tender');
    mkdirSync(join(p, 'vendors/acme'), { recursive: true });
    writeFileSync(join(p, 'ARC-001-REQ-v1.0.md'), doc('ARC-001-REQ-v1.0', 'OFFICIAL'));
    writeFileSync(join(p, 'ARC-001-EVAL-v1.0.md'), doc('ARC-001-EVAL-v1.0', 'OFFICIAL-SENSITIVE'));
    writeFileSync(join(p, 'vendors/acme/proposal.md'), '# Acme proposal\n');
    writeFileSync(join(p, 'vendors/scores.json'), JSON.stringify({
      projectId: '001',
      criteria: [{ id: 'C1', category: 'Technical', weight: 1 }],
      vendors: {
        acme: { displayName: 'Acme Ltd', scores: [{ criterionId: 'C1', score: 3 }], totalWeighted: 3 },
        beta: { displayName: 'Beta plc', scores: [{ criterionId: 'C1', score: 1 }], totalWeighted: 1 },
      },
    }));
    if (priorLlms !== null) {
      mkdirSync(join(dir, 'docs'), { recursive: true });
      writeFileSync(join(dir, 'docs/llms.txt'), priorLlms);
    }
    fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const manifestOf = (dir) => JSON.parse(readFileSync(join(dir, 'docs/manifest.json'), 'utf8'));
const scoresIn = (dir) => manifestOf(dir).projects.some((p) => p.vendorScores);

test('defaults: no vendor ranking, no llms.txt, confidentiality section shown', () => {
  withRepo((dir) => {
    const ctx = runHook(dir, '/arckit:pages');
    assert.equal(scoresIn(dir), false, 'vendor ranking leaked into manifest.json');
    assert.equal(existsSync(join(dir, 'docs/llms.txt')), false);
    assert.match(ctx, /### CONFIDENTIALITY/);
    assert.match(ctx, /Nothing has been published/);
    assert.match(ctx, /Vendor scores: \*\*left out\*\* \(2 scored vendor/);
    assert.match(ctx, /llms\.txt.*not written \(opt in with LLMS=true\)/);
  });
});

test('artefacts marked above OFFICIAL are named', () => {
  withRepo((dir) => {
    const ctx = runHook(dir, '/arckit:pages');
    assert.match(ctx, /\*\*1 artefact\(s\) are marked above OFFICIAL\*\*/);
    assert.match(ctx, /ARC-001-EVAL-v1\.0\.md` \(OFFICIAL-SENSITIVE\)/);
    assert.doesNotMatch(ctx, /ARC-001-REQ-v1\.0\.md` \(OFFICIAL\)/);
  });
});

test('opt-in flags include the ranking and write llms.txt', () => {
  withRepo((dir) => {
    const ctx = runHook(dir, '/arckit:pages LLMS=true VENDOR_SCORES=true');
    assert.equal(scoresIn(dir), true);
    const llms = readFileSync(join(dir, 'docs/llms.txt'), 'utf8');
    assert.ok(llms.includes(MARKER));
    assert.match(ctx, /Vendor scores: \*\*included\*\*/);
  });
});

test('an llms.txt generated by an earlier run is removed by default', () => {
  withRepo((dir) => {
    const ctx = runHook(dir, '/arckit:pages');
    assert.equal(existsSync(join(dir, 'docs/llms.txt')), false);
    assert.match(ctx, /removed — an earlier run generated it/);
  }, { priorLlms: `${MARKER}\n# old index\n` });
});

test('a hand-curated llms.txt is never touched', () => {
  const curated = '# My curated index\n';
  withRepo((dir) => {
    runHook(dir, '/arckit:pages');
    assert.equal(readFileSync(join(dir, 'docs/llms.txt'), 'utf8'), curated);
  }, { priorLlms: curated });
});

test('flags in the command body do not count as opt-in', () => {
  withRepo((dir) => {
    const body = [
      '---', 'description: Generate documentation site with governance dashboard', '---',
      '**User Request**: ',
      'Pass LLMS=true to write docs/llms.txt and VENDOR_SCORES=true to include the ranking.',
    ].join('\n');
    runHook(dir, body);
    assert.equal(scoresIn(dir), false);
    assert.equal(existsSync(join(dir, 'docs/llms.txt')), false);
  });
});

test('flags in the expanded body User Request line do count', () => {
  withRepo((dir) => {
    const body = [
      '---', 'description: Generate documentation site with governance dashboard', '---',
      '**User Request**: VENDOR_SCORES=true',
    ].join('\n');
    runHook(dir, body);
    assert.equal(scoresIn(dir), true);
  });
});
