/**
 * Provenance stamping for namespaced overlay commands.
 *
 * Two bugs made overlay artefacts silently lose their Build Provenance block:
 *
 * 1. REGRESSION (v6.7.1). The publish-time namespacing rewrite also rewrites
 *    template footers, so an artefact from a published overlay template says
 *    `/arckit-repo:repo-audit`. The footer pattern required `:` or `.`
 *    immediately after `arckit`, so it matched nothing.
 * 2. PRE-EXISTING. readCommandFrontmatter only looked in
 *    <plugin-root>/commands/, so none of the 105 overlay commands could
 *    resolve their `effort:` even with a matching footer.
 *
 * Both were invisible in the source tree, where footers still carry the
 * portable `/arckit:X` form. Only published artefacts were affected, which is
 * why nothing caught it.
 *
 * NOTE the filename: CI runs `tests/plugin/*.test.mjs`, so a `test_*.mjs` name
 * would never execute here.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';

const HOOK = resolve('plugins/arckit-claude/hooks/provenance-stamp.mjs');

function stamp(footer) {
  const root = mkdtempSync(join(tmpdir(), 'prov-'));
  const dir = join(root, 'projects', '001-t');
  mkdirSync(dir, { recursive: true });
  const file = join(dir, 'ARC-001-REQ-v1.0.md');
  writeFileSync(
    file,
    `# T\n\n---\n\n**Generated by**: ArcKit \`${footer}\` command\n**Model**: claude-opus-5\n`,
  );
  execFileSync('node', [HOOK], {
    input: JSON.stringify({
      tool_name: 'Write',
      cwd: root,
      tool_input: { file_path: file },
    }),
    encoding: 'utf8',
  });
  return readFileSync(file, 'utf8');
}

function requestedEffort(content) {
  const m = content.match(/\| Requested Effort \| `([^`]+)` \|/);
  return m ? m[1] : null;
}

test('core command in the portable form still stamps', () => {
  const out = stamp('/arckit:adr');
  assert.match(out, /## Build Provenance/);
  assert.equal(requestedEffort(out), 'high');
});

test('legacy dot form still stamps', () => {
  assert.match(stamp('/arckit.adr'), /## Build Provenance/);
});

test('namespaced overlay command stamps (regression: v6.7.1)', () => {
  const out = stamp('/arckit-repo:repo-audit');
  assert.match(
    out,
    /## Build Provenance/,
    'published overlay artefacts lost provenance when footers gained the namespace',
  );
});

test('namespaced overlay resolves effort from its OWN plugin, not core', () => {
  // repo-audit is `effort: max`; core's default commands are `high`. Getting
  // `max` proves the lookup reached plugins/arckit-repo/commands/, not just
  // plugins/arckit-claude/commands/.
  assert.equal(requestedEffort(stamp('/arckit-repo:repo-audit')), 'max');
});

test('a different overlay resolves too', () => {
  const out = stamp('/arckit-uae:uae-ai-charter');
  assert.match(out, /## Build Provenance/);
  assert.equal(requestedEffort(out), 'high');
});

test('unknown command still stamps nothing rather than throwing', () => {
  const out = stamp('/arckit-nope:does-not-exist');
  assert.doesNotMatch(out, /## Build Provenance/);
});

test('footer pattern accepts all three shapes', async () => {
  const src = readFileSync(HOOK, 'utf8');
  const m = src.match(/content\.match\((\/Generated by[^\n]+?)\);/);
  assert.ok(m, 'footer pattern not found in provenance-stamp.mjs');
  const re = new RegExp(m[1].replace(/^\//, '').replace(/\/i$/, ''), 'i');
  for (const form of ['/arckit:adr', '/arckit.adr', '/arckit-repo:repo-audit']) {
    assert.match(
      `**Generated by**: ArcKit \`${form}\` command`,
      re,
      `pattern rejects ${form}`,
    );
  }
});
