#!/usr/bin/env python3
"""Check that every `create-project.sh` invocation in a command, agent or skill
body is one the script would actually accept.

`create-project.sh` is create-only and takes its name as `--name "NAME"`. It has
no positional argument and no lookup mode. Two spellings were nevertheless in
wide use, and both exit 1 without producing a project:

    create-project.sh --json <project-name>   # 32 files -- Unknown option (#777)
    create-project.sh --json                  # 9 files  -- name required (#775)

The second was worse than a failed call: five of those sites described it as a
way to *look up* the current project, so the model was told to read a path out
of a response that never arrives. Nothing noticed, because these are prompts
rather than scripts -- the model gets a usage dump, improvises a directory, and
the command appears to work while skipping everything `create-project.sh` does
beyond `mkdir` (the external/ README, the 000-global scaffolding, and a project
README carrying the correct ARC-{NNN}-* filename list).

Rules, applied only to text inside a code span or fenced block, so that prose
mentions like "the path returned by create-project.sh" are left alone:

  1. an invocation carrying any flag must carry `--name`
  2. no positional argument may follow the script path

Usage:
    python3 scripts/check-create-project-invocations.py
    python3 scripts/check-create-project-invocations.py --check   # CI alias
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Command/agent/skill bodies across every source plugin. The publish-layout
# mirror under arckit-claude/plugins/ is generated by sync-claude-plugin-layout.py
# and is checked through its source, not directly.
SEARCH_ROOTS = (
    REPO_ROOT / "plugins",
    REPO_ROOT / "docs/guides",
)

MIRROR = REPO_ROOT / "plugins/arckit-claude/plugins"

# `create-project.sh` plus the rest of the code span it sits in. The optional
# trailing quote closes a quoted script path -- `bash "${CLAUDE_PLUGIN_ROOT}/
# scripts/bash/create-project.sh" --name ...` -- which otherwise leaves a stray
# quote at the head of the argument tail and pairs up with the next one.
INVOCATION = re.compile(r"create-project\.sh[\"']?(?P<args>[^`\n]*)")

# Inline code spans and fenced-block bodies.
CODE_SPAN = re.compile(r"`([^`\n]+)`")
FENCED = re.compile(r"^```[^\n]*\n(.*?)^```", re.MULTILINE | re.DOTALL)

KNOWN_FLAGS = {"--json", "--force", "--help", "-h", "--name"}


def code_regions(text: str) -> list[str]:
    regions = [m.group(1) for m in CODE_SPAN.finditer(text)]
    for block in FENCED.finditer(text):
        regions.extend(block.group(1).splitlines())
    return regions


def split_args(args: str) -> list[str]:
    """Split an argument tail, treating a quoted value as one word."""
    return re.findall(r'"[^"]*"|\'[^\']*\'|\S+', args)


def problems_in(region: str) -> list[str]:
    found = []
    for match in INVOCATION.finditer(region):
        words = split_args(match.group("args"))
        if not words:
            continue  # bare mention, e.g. `create-project.sh`

        if not [w for w in words if w.startswith("-")]:
            continue  # not an invocation line

        # A value belongs to the flag before it; everything else is positional.
        positionals = []
        expects_value = False
        for word in words:
            if expects_value:
                expects_value = False
                continue
            if word.startswith("-"):
                expects_value = word == "--name"
                if word not in KNOWN_FLAGS:
                    found.append(f"unknown flag {word}: create-project.sh{match.group('args')}")
                continue
            positionals.append(word)

        if positionals:
            found.append(
                f"positional argument {positionals[0]} (the name must be passed as "
                f'--name "NAME"): create-project.sh{match.group("args")}'
            )
        elif "--name" not in words:
            found.append(
                "no --name, so the script exits 1 without returning a path: "
                f"create-project.sh{match.group('args')}"
            )
    return found


def iter_files():
    for root in SEARCH_ROOTS:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.md")):
            if MIRROR in path.parents:
                continue
            yield path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="CI-friendly alias")
    parser.parse_args()

    failures: list[tuple[Path, str]] = []
    scanned = 0
    for path in iter_files():
        text = path.read_text(encoding="utf-8")
        if "create-project.sh" not in text:
            continue
        scanned += 1
        for region in code_regions(text):
            for problem in problems_in(region):
                failures.append((path.relative_to(REPO_ROOT), problem))

    if failures:
        print(f"{len(failures)} bad create-project.sh invocation(s):\n", file=sys.stderr)
        for path, problem in failures:
            print(f"  {path}: {problem}", file=sys.stderr)
        print(
            '\ncreate-project.sh is create-only. Use --json --name "<project-name>", '
            "and resolve an existing project from the ArcKit Project Context instead "
            "(see #775, #777).",
            file=sys.stderr,
        )
        return 1

    print(f"create-project.sh invocations OK ({scanned} files reference it)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
