#!/usr/bin/env python3
"""Guard docs/llms.txt against drift.

docs/llms.txt is the llmstxt.org index for arckit.org. It is deliberately
hand-curated: sync-guides.mjs only overwrites an llms.txt carrying the
`<!-- Generated by ArcKit /arckit:pages -->` marker, and ours does not, because
it also indexes articles, roles, use cases and test repos that no generator
knows about.

Hand-curated plus unguarded is why it drifted badly: by the time this script was
written it was missing 41 commands outright, and 45 of its 49 GitHub links still
pointed at the pre-v6 `arckit-claude/commands/...` layout and 404'd.

Three checks, all cheap and all deterministic:

  1. Every command in plugins/*/commands/*.md is referenced — by `/arckit:<name>`,
     by a link to its command file, or by a link to its guide.
  2. Every arc-kit repo path linked from llms.txt actually exists.
  3. Every distribution format ArcKit ships is named.

Exit 0 on success, 1 with a specific remediation list on failure.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LLMS = REPO / "docs" / "llms.txt"

# Commands deliberately absent from the public index, with the reason.
# Keep this small — the default answer is "add it to llms.txt", not "exempt it".
EXEMPT_COMMANDS: dict[str, str] = {}

# Distribution formats that must be named in the intro prose. Sourced from
# CLAUDE.md's "Nine distribution formats" list.
REQUIRED_FORMATS = [
    "Claude Code",
    "Gemini CLI",
    "Copilot",
    "Codex CLI",
    "OpenCode CLI",
    "Mistral Vibe",
    "Paperclip",
    "Kimi Code CLI",
]

# Links to other repositories under the tractorjuice org are not checkable here.
FOREIGN_REPO_PREFIXES = ("https://github.com/tractorjuice/arckit-",)


def tracked_files() -> set[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout
    return {line for line in out.split("\n") if line}


def main() -> int:
    if not LLMS.is_file():
        print(f"[FAIL] {LLMS.relative_to(REPO)} does not exist", file=sys.stderr)
        return 1

    text = LLMS.read_text(encoding="utf-8")
    tracked = tracked_files()
    failures: list[str] = []

    # ---- 1. every command is referenced -------------------------------------
    commands: dict[str, str] = {}
    for path in sorted(tracked):
        m = re.match(r"^plugins/(arckit-[a-z0-9-]+)/commands/([a-z0-9.\-]+)\.md$", path)
        if m:
            commands[m.group(2)] = path

    missing = []
    for name, path in sorted(commands.items()):
        if name in EXEMPT_COMMANDS:
            continue
        patterns = [
            rf"/arckit(?:-[a-z-]+)?:{re.escape(name)}\b",
            rf"commands/{re.escape(name)}\.md",
            rf"guides/{re.escape(name)}\.md",
        ]
        if not any(re.search(p, text) for p in patterns):
            missing.append((name, path))

    if missing:
        failures.append(
            f"{len(missing)} command(s) are not referenced in docs/llms.txt:\n"
            + "\n".join(f"    {n:<28} ({p})" for n, p in missing)
            + "\n  Add each to the appropriate section, or add it to EXEMPT_COMMANDS with a reason."
        )

    # ---- 2. every linked repo path exists -----------------------------------
    dead = []
    for url in re.findall(r"https://github\.com/tractorjuice/arc-kit/blob/main/([^)\s]+)", text):
        path = url.split("#", 1)[0]
        if path and path not in tracked:
            dead.append(path)

    if dead:
        uniq = sorted(set(dead))
        failures.append(
            f"{len(uniq)} link(s) in docs/llms.txt point at paths that do not exist:\n"
            + "\n".join(f"    {p}" for p in uniq)
            + "\n  Overlay commands live at plugins/arckit-<x>/commands/<name>.md since v6."
        )

    # ---- 3. every distribution format is named ------------------------------
    unnamed = [f for f in REQUIRED_FORMATS if f not in text]
    if unnamed:
        failures.append(
            "distribution format(s) missing from the docs/llms.txt intro: "
            + ", ".join(unnamed)
        )

    if failures:
        print("[FAIL] docs/llms.txt is out of sync:\n", file=sys.stderr)
        for f in failures:
            print(f"  - {f}\n", file=sys.stderr)
        return 1

    exempt_note = f", {len(EXEMPT_COMMANDS)} exempt" if EXEMPT_COMMANDS else ""
    print(
        f"llms.txt check OK: {len(commands)} command(s) referenced{exempt_note}; "
        f"all repo links resolve; all {len(REQUIRED_FORMATS)} distribution formats named."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
