#!/usr/bin/env python3
"""Generate one static share page per article, so link previews show the article.

`docs/article-viewer.html` renders every article in JavaScript, so its
`og:title` and `og:image` are the same generic "Article - ArcKit" card for all
of them. LinkedIn, Discord, Slack and Medium fetch previews without running
JavaScript, which is why every shared article link showed that card instead of
the article's own title and hero image (seen on the Show Your Working launch,
23 September 2026).

This script reads the cards on `docs/articles.html` (slug, title, summary,
hero image) and writes `docs/share/<slug>.html` for each: a page carrying that
article's Open Graph and Twitter tags, which immediately redirects readers to
`article-viewer.html?a=<slug>`. Share `https://arckit.org/share/<slug>.html`
on social channels; the viewer link is unchanged for everything else.

    python3 scripts/generate-article-share-pages.py          # write pages
    python3 scripts/generate-article-share-pages.py --check  # CI: exit 1 if stale

`--check` fails when a card has no page, a page is out of date with its card,
or a page exists for an article that is no longer listed.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LISTING = REPO_ROOT / "docs" / "articles.html"
SHARE_DIR = REPO_ROOT / "docs" / "share"
SITE = "https://arckit.org"
FALLBACK_IMAGE = f"{SITE}/og-image.png"

CARD_RE = re.compile(r'<article class="app-article-card">(.*?)</article>', re.S)
SLUG_RE = re.compile(r'article-viewer\.html\?a=([A-Za-z0-9._-]+)"')
IMG_RE = re.compile(r'<img src="([^"]+)"(?:\s+alt="([^"]*)")?')
TITLE_RE = re.compile(r'app-article-card__title">(.*?)</h2>', re.S)
SUMMARY_RE = re.compile(r'app-article-card__summary">(.*?)</p>', re.S)


def text(fragment: str) -> str:
    """Card HTML to plain text: drop tags, decode entities, collapse whitespace."""
    return " ".join(html.unescape(re.sub(r"<[^>]+>", "", fragment)).split())


def cards() -> list[dict[str, str]]:
    out = []
    for block in CARD_RE.findall(LISTING.read_text(encoding="utf-8")):
        slug = SLUG_RE.search(block)
        title = TITLE_RE.search(block)
        if not slug or not title:
            continue
        img = IMG_RE.search(block)
        summary = SUMMARY_RE.search(block)
        out.append({
            "slug": slug.group(1),
            "title": text(title.group(1)),
            "summary": text(summary.group(1)) if summary else "",
            "image": f"{SITE}/{img.group(1)}" if img and not img.group(1).endswith(".svg") else FALLBACK_IMAGE,
            "alt": text(img.group(2) or "") if img else "",
        })
    return out


def render(card: dict[str, str]) -> str:
    e = lambda s: html.escape(s, quote=True)  # noqa: E731
    slug = card["slug"]
    viewer = f"article-viewer.html?a={slug}"
    share_url = f"{SITE}/share/{slug}.html"
    title, summary, image = e(card["title"]), e(card["summary"]), e(card["image"])
    alt = e(card["alt"] or card["title"])
    return f"""<!DOCTYPE html>
<!-- Generated by scripts/generate-article-share-pages.py from docs/articles.html. Do not edit. -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title} | ArcKit</title>
    <meta name="description" content="{summary}">
    <link rel="canonical" href="{SITE}/{e(viewer)}">
    <meta property="og:type" content="article">
    <meta property="og:site_name" content="ArcKit">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{summary}">
    <meta property="og:url" content="{share_url}">
    <meta property="og:image" content="{image}">
    <meta property="og:image:alt" content="{alt}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{summary}">
    <meta name="twitter:image" content="{image}">
    <meta http-equiv="refresh" content="0; url=../{e(viewer)}">
    <script>location.replace("../{viewer}" + location.search.replace(/^\\?/, "&") + location.hash);</script>
</head>
<body>
    <p><a href="../{e(viewer)}">{title}</a></p>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="report stale pages and exit 1 instead of writing")
    args = parser.parse_args()

    wanted = {c["slug"]: render(c) for c in cards()}
    existing = {p.stem: p for p in SHARE_DIR.glob("*.html")} if SHARE_DIR.exists() else {}
    problems = []

    for slug, content in wanted.items():
        path = SHARE_DIR / f"{slug}.html"
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            problems.append(f"{'stale' if path.exists() else 'missing'}: docs/share/{slug}.html")
        else:
            SHARE_DIR.mkdir(exist_ok=True)
            path.write_text(content, encoding="utf-8")
    for slug, path in existing.items():
        if slug not in wanted:
            if args.check:
                problems.append(f"orphan (no card on docs/articles.html): docs/share/{slug}.html")
            else:
                path.unlink()

    if problems:
        print("Article share pages are out of date. Run: python3 scripts/generate-article-share-pages.py")
        for p in problems:
            print(f"  ✗ {p}")
        return 1
    print(f"Article share pages OK ({len(wanted)} articles).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
